all:
	node test_regexp
	node test_modules
	node test_scripts
	node test_functions
	node test_statements
	node test_expressions
	node test_tokenizer
	node test_sourcetext
	node test_unicode
	node test_selfcode
